
name: android

on:
  push:
    branches:
      - main
    tags:
      - release*

    paths-ignore:
    - 'README.md'
    - '.vscode/**'
    - '.gitignore'
    - '.gitattributes'
    - '.editorconfig'

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     matrix:
  #       arch: ["arm", "arm64"]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build
  #       run: ./build.sh ${{ matrix.arch }} android

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: sobar-android-${{ matrix.arch }}-r${{ env.SobarREV }}-${{ env.SobarCOMMIT }}
  #         path: dist/${{ matrix.arch }}
  #         #retention-days: 1
