name: macOS

on:
  push:
    paths-ignore:
    - 'README.md'
    - '.vscode/**'
    - '.gitignore'
    - '.gitattributes'
    - '.editorconfig'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: ["x64", "arm64"]
    outputs:
      suffix: ${{ steps.filename.outputs.suffix }}
    if: endsWith(github.ref, 'mac') || (!endsWith(github.ref, 'android') && !endsWith(github.ref, 'ios') && !endsWith(github.ref, 'linux') && !endsWith(github.ref, 'windows'))

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Build
        run: ./build.sh ${{ matrix.arch }} mac

      - id: filename
        run: echo "::set-output name=suffix::-r${{ github.run_number }}-${{ env.SobarCOMMIT }}"

      - uses: actions/upload-artifact@v2
        with:
          name: sobar-mac-${{ matrix.arch }}-r${{ github.run_number }}-${{ env.SobarCOMMIT }}
          path: dist/${{ matrix.arch }}
          #retention-days: 1

  lipo:
    runs-on: macos-latest
    timeout-minutes: 10
    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: sobar-mac-x64${{ needs.build.outputs.suffix }}
          path: x64
      
      - uses: actions/download-artifact@master
        with:
          name: sobar-mac-arm64${{ needs.build.outputs.suffix }}
          path: arm64

      - name: Lipo architecture libraries
        run: |
          mkdir -p dist/universal/include/
          cp x64/include/sobar.h dist/universal/include/
          mkdir -p dist/universal/lib/mac/universal/
          lipo -create x64/lib/mac/x64/libsobar.dylib arm64/lib/mac/arm64/libsobar.dylib -output dist/universal/lib/mac/universal/libsobar.dylib

      - uses: actions/upload-artifact@v2
        with:
          name: sobar-mac-universal${{ needs.build.outputs.suffix }}
          path: dist/universal
          #retention-days: 1
