
name: CI

on:
  push:
    branches:
      - main
    tags:
      - release*

    paths-ignore:
    - 'README.md'
    - '.vscode/**'
    - '.gitignore'
    - '.gitattributes'
    - '.editorconfig'

jobs:
  build_windows:
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: ["x86", "x64"]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: .\build.ps1 ${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: sobar-windows-${{ matrix.arch }}-r${{ env.SobarREV }}-${{ env.SobarCOMMIT }}
          path: dist/${{ matrix.arch }}
          #retention-days: 1

  build_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: ["x86", "x64"]

    steps:
      - uses: actions/checkout@v2

      # Just installing ninja-build is enough for GitHub Actions
      # Not to use ./build/install-build-deps.sh
      - name: Prerequisites
        run: sudo apt install ninja-build gcc-multilib g++-multilib

      - name: Build
        run: ./build.sh ${{ matrix.arch }} linux

      - uses: actions/upload-artifact@v2
        with:
          name: sobar-linux-${{ matrix.arch }}-r${{ env.SobarREV }}-${{ env.SobarCOMMIT }}
          path: dist/${{ matrix.arch }}
          #retention-days: 1

  # build_android:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     matrix:
  #       arch: ["arm", "arm64"]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build
  #       run: ./build.sh ${{ matrix.arch }} android

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: sobar-android-${{ matrix.arch }}-r${{ env.SobarREV }}-${{ env.SobarCOMMIT }}
  #         path: dist/${{ matrix.arch }}
  #         #retention-days: 1

  build_mac:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: ["x64", "arm64"]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./build.sh ${{ matrix.arch }} mac

      - uses: actions/upload-artifact@v2
        with:
          name: sobar-mac-${{ matrix.arch }}-r${{ env.SobarREV }}-${{ env.SobarCOMMIT }}
          path: dist/${{ matrix.arch }}
          #retention-days: 1
