
name: windows

on:
  push:
    branches:
      - main
    tags:
      - release*

    paths-ignore:
    - 'README.md'
    - '.vscode/**'
    - '.gitignore'
    - '.gitattributes'
    - '.editorconfig'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: ["x86", "x64"]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: .\build.ps1 ${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: sobar-windows-${{ matrix.arch }}-r${{ env.SobarREV }}-${{ env.SobarCOMMIT }}
          path: dist/${{ matrix.arch }}
          #retention-days: 1
